# Generated by Django 6.0.3 on 2026-03-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainer_photos/'),
        ),
    ]
